name: absen_smkn1_punggelan

description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  dio: ^5.5.0+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  geolocator: ^10.0.0
  image_picker: ^1.0.7
  camera: ^0.10.5+5
  intl: ^0.19.0
  flutter_local_notifications: ^15.1.0+1
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  flutter_osm_plugin: ^0.70.4
  device_info_plus: ^9.1.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  flutter_timezone: ^1.0.8
  flutter_face_api: ^6.2.2
  flutter_face_core_basic: ^6.2.1
  http: ^1.1.0
  timezone: ^0.9.4
  image_cropper: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_sekolah.png
    - assets/images/google_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
